/**
 * Products seed data for Kandukuru Supermarket
 * Comprehensive product catalog for Indian supermarket
 */

module.exports = [
  // Rice & Grains
  {
    name: 'Basmati Rice Premium',
    price: 180,
    mrp: 200,
    discount: 10,
    description: 'Premium quality basmati rice with long grains and aromatic fragrance',
    categoryName: 'Rice & Grains',
    subcategory: 'Basmati Rice',
    brand: 'India Gate',
    unit: 'kg',
    unitSize: '1',
    stock: 50,
    minStock: 10,
    isFeatured: true,
    isOrganic: false,
    tags: ['rice', 'basmati', 'premium', 'aromatic'],
    imageUrl: '/images/products/basmati-rice.jpg',
    nutritionalInfo: {
      calories: 130,
      protein: '2.7g',
      carbs: '28g',
      fat: '0.3g',
      fiber: '0.4g'
    },
    supplier: {
      name: 'Local Rice Distributor',
      contact: '+91-9876543210',
      address: 'Rice Market, Kurnool'
    }
  },
  {
    name: 'Sona Masoori Rice',
    price: 85,
    mrp: 90,
    discount: 5,
    description: 'Premium sona masoori rice, perfect for daily meals',
    categoryName: 'Rice & Grains',
    subcategory: 'Non-Basmati Rice',
    brand: 'Fortune',
    unit: 'kg',
    unitSize: '1',
    stock: 75,
    minStock: 15,
    isFeatured: true,
    tags: ['rice', 'sona masoori', 'daily use'],
    imageUrl: '/images/products/sona-masoori.jpg'
  },
  {
    name: 'Wheat Flour (Atta)',
    price: 45,
    mrp: 50,
    discount: 10,
    description: 'Fresh ground wheat flour for chapati and bread making',
    categoryName: 'Flour & Atta',
    brand: 'Aashirvaad',
    unit: 'kg',
    unitSize: '1',
    stock: 100,
    minStock: 20,
    isFeatured: true,
    tags: ['wheat', 'flour', 'atta', 'chapati'],
    imageUrl: '/images/products/wheat-flour.jpg'
  },

  // Pulses & Lentils
  {
    name: 'Toor Dal (Arhar)',
    price: 120,
    mrp: 130,
    discount: 7,
    description: 'Premium quality toor dal, rich in protein',
    categoryName: 'Pulses & Lentils',
    brand: 'Tata Sampann',
    unit: 'kg',
    unitSize: '1',
    stock: 60,
    minStock: 15,
    tags: ['dal', 'toor', 'protein', 'lentils'],
    imageUrl: '/images/products/toor-dal.jpg'
  },
  {
    name: 'Moong Dal',
    price: 110,
    mrp: 120,
    discount: 8,
    description: 'Yellow moong dal, easy to digest and nutritious',
    categoryName: 'Pulses & Lentils',
    brand: 'MDH',
    unit: 'kg',
    unitSize: '1',
    stock: 45,
    minStock: 10,
    tags: ['dal', 'moong', 'yellow', 'nutritious'],
    imageUrl: '/images/products/moong-dal.jpg'
  },
  {
    name: 'Chana Dal',
    price: 95,
    mrp: 105,
    discount: 9,
    description: 'Split chickpeas, perfect for various Indian dishes',
    categoryName: 'Pulses & Lentils',
    brand: 'Everest',
    unit: 'kg',
    unitSize: '1',
    stock: 40,
    minStock: 10,
    tags: ['dal', 'chana', 'chickpeas'],
    imageUrl: '/images/products/chana-dal.jpg'
  },

  // Cooking Oil
  {
    name: 'Sunflower Oil',
    price: 140,
    mrp: 150,
    discount: 6,
    description: 'Refined sunflower oil for healthy cooking',
    categoryName: 'Cooking Oil',
    brand: 'Fortune',
    unit: 'liter',
    unitSize: '1',
    stock: 80,
    minStock: 15,
    isFeatured: true,
    tags: ['oil', 'sunflower', 'cooking', 'healthy'],
    imageUrl: '/images/products/sunflower-oil.jpg'
  },
  {
    name: 'Mustard Oil',
    price: 160,
    mrp: 170,
    discount: 5,
    description: 'Pure mustard oil, traditional and healthy',
    categoryName: 'Cooking Oil',
    brand: 'Patanjali',
    unit: 'liter',
    unitSize: '1',
    stock: 50,
    minStock: 10,
    tags: ['oil', 'mustard', 'traditional', 'healthy'],
    imageUrl: '/images/products/mustard-oil.jpg'
  },

  // Fresh Vegetables
  {
    name: 'Onions',
    price: 30,
    mrp: 35,
    discount: 14,
    description: 'Fresh red onions, essential for Indian cooking',
    categoryName: 'Root Vegetables',
    unit: 'kg',
    unitSize: '1',
    stock: 200,
    minStock: 50,
    isFeatured: true,
    tags: ['onion', 'vegetables', 'fresh', 'daily use'],
    imageUrl: '/images/products/onions.jpg'
  },
  {
    name: 'Potatoes',
    price: 25,
    mrp: 30,
    discount: 16,
    description: 'Fresh potatoes, good for various dishes',
    categoryName: 'Root Vegetables',
    unit: 'kg',
    unitSize: '1',
    stock: 300,
    minStock: 75,
    isFeatured: true,
    tags: ['potato', 'vegetables', 'fresh'],
    imageUrl: '/images/products/potatoes.jpg'
  },
  {
    name: 'Tomatoes',
    price: 40,
    mrp: 45,
    discount: 11,
    description: 'Fresh red tomatoes, perfect for curries and salads',
    categoryName: 'Fresh Vegetables',
    unit: 'kg',
    unitSize: '1',
    stock: 150,
    minStock: 30,
    isFeatured: true,
    tags: ['tomato', 'vegetables', 'fresh', 'red'],
    imageUrl: '/images/products/tomatoes.jpg'
  },
  {
    name: 'Green Chillies',
    price: 60,
    mrp: 70,
    discount: 14,
    description: 'Fresh green chillies for spicing up your dishes',
    categoryName: 'Fresh Vegetables',
    unit: 'kg',
    unitSize: '0.25',
    stock: 50,
    minStock: 10,
    tags: ['chilli', 'green', 'spicy', 'fresh'],
    imageUrl: '/images/products/green-chillies.jpg'
  },
  {
    name: 'Spinach (Palak)',
    price: 20,
    mrp: 25,
    discount: 20,
    description: 'Fresh spinach leaves, rich in iron and vitamins',
    categoryName: 'Leafy Vegetables',
    unit: 'piece',
    unitSize: '1',
    stock: 100,
    minStock: 20,
    tags: ['spinach', 'palak', 'leafy', 'iron', 'healthy'],
    imageUrl: '/images/products/spinach.jpg'
  },
  {
    name: 'Coriander Leaves',
    price: 15,
    mrp: 20,
    discount: 25,
    description: 'Fresh coriander leaves for garnishing and flavoring',
    categoryName: 'Leafy Vegetables',
    unit: 'piece',
    unitSize: '1',
    stock: 80,
    minStock: 15,
    tags: ['coriander', 'leaves', 'garnish', 'fresh'],
    imageUrl: '/images/products/coriander.jpg'
  },

  // Fresh Fruits
  {
    name: 'Bananas',
    price: 50,
    mrp: 55,
    discount: 9,
    description: 'Fresh yellow bananas, perfect for breakfast',
    categoryName: 'Seasonal Fruits',
    unit: 'dozen',
    unitSize: '1',
    stock: 100,
    minStock: 20,
    isFeatured: true,
    tags: ['banana', 'fruit', 'yellow', 'healthy'],
    imageUrl: '/images/products/bananas.jpg'
  },
  {
    name: 'Apples (Shimla)',
    price: 180,
    mrp: 200,
    discount: 10,
    description: 'Fresh Shimla apples, crispy and sweet',
    categoryName: 'Seasonal Fruits',
    unit: 'kg',
    unitSize: '1',
    stock: 80,
    minStock: 15,
    isFeatured: true,
    tags: ['apple', 'shimla', 'crispy', 'sweet'],
    imageUrl: '/images/products/apples.jpg'
  },
  {
    name: 'Oranges',
    price: 80,
    mrp: 90,
    discount: 11,
    description: 'Juicy oranges, rich in Vitamin C',
    categoryName: 'Seasonal Fruits',
    unit: 'kg',
    unitSize: '1',
    stock: 120,
    minStock: 25,
    tags: ['orange', 'juicy', 'vitamin c', 'citrus'],
    imageUrl: '/images/products/oranges.jpg'
  },
  {
    name: 'Almonds',
    price: 650,
    mrp: 700,
    discount: 7,
    description: 'Premium California almonds, rich in nutrients',
    categoryName: 'Dry Fruits & Nuts',
    unit: 'kg',
    unitSize: '0.5',
    stock: 30,
    minStock: 5,
    isFeatured: true,
    tags: ['almonds', 'dry fruits', 'nuts', 'premium'],
    imageUrl: '/images/products/almonds.jpg'
  },
  {
    name: 'Cashew Nuts',
    price: 800,
    mrp: 850,
    discount: 5,
    description: 'Premium cashew nuts, perfect for snacking',
    categoryName: 'Dry Fruits & Nuts',
    unit: 'kg',
    unitSize: '0.5',
    stock: 25,
    minStock: 5,
    tags: ['cashew', 'nuts', 'premium', 'snacking'],
    imageUrl: '/images/products/cashews.jpg'
  },

  // Dairy & Eggs
  {
    name: 'Fresh Milk (Toned)',
    price: 25,
    mrp: 25,
    discount: 0,
    description: 'Fresh toned milk, delivered daily',
    categoryName: 'Milk & Yogurt',
    brand: 'Amul',
    unit: 'liter',
    unitSize: '0.5',
    stock: 200,
    minStock: 50,
    isFeatured: true,
    tags: ['milk', 'fresh', 'toned', 'daily'],
    imageUrl: '/images/products/fresh-milk.jpg'
  },
  {
    name: 'Curd (Dahi)',
    price: 30,
    mrp: 35,
    discount: 14,
    description: 'Fresh homemade style curd',
    categoryName: 'Milk & Yogurt',
    brand: 'Mother Dairy',
    unit: 'kg',
    unitSize: '0.5',
    stock: 150,
    minStock: 30,
    tags: ['curd', 'dahi', 'fresh', 'homemade'],
    imageUrl: '/images/products/curd.jpg'
  },
  {
    name: 'Paneer',
    price: 320,
    mrp: 350,
    discount: 8,
    description: 'Fresh cottage cheese, perfect for Indian dishes',
    categoryName: 'Cheese & Butter',
    brand: 'Amul',
    unit: 'kg',
    unitSize: '0.2',
    stock: 50,
    minStock: 10,
    isFeatured: true,
    tags: ['paneer', 'cheese', 'cottage', 'fresh'],
    imageUrl: '/images/products/paneer.jpg'
  },
  {
    name: 'Butter',
    price: 55,
    mrp: 60,
    discount: 8,
    description: 'Fresh butter, perfect for bread and cooking',
    categoryName: 'Cheese & Butter',
    brand: 'Amul',
    unit: 'piece',
    unitSize: '100g',
    stock: 80,
    minStock: 15,
    tags: ['butter', 'fresh', 'cooking'],
    imageUrl: '/images/products/butter.jpg'
  },
  {
    name: 'Farm Fresh Eggs',
    price: 60,
    mrp: 65,
    discount: 7,
    description: 'Fresh farm eggs, rich in protein',
    categoryName: 'Eggs',
    unit: 'dozen',
    unitSize: '1',
    stock: 200,
    minStock: 40,
    isFeatured: true,
    tags: ['eggs', 'farm fresh', 'protein'],
    imageUrl: '/images/products/eggs.jpg'
  },

  // Spices & Condiments
  {
    name: 'Turmeric Powder',
    price: 45,
    mrp: 50,
    discount: 10,
    description: 'Pure turmeric powder, essential Indian spice',
    categoryName: 'Spices & Condiments',
    brand: 'Everest',
    unit: 'packet',
    unitSize: '100g',
    stock: 100,
    minStock: 20,
    tags: ['turmeric', 'spice', 'powder', 'essential'],
    imageUrl: '/images/products/turmeric.jpg'
  },
  {
    name: 'Red Chilli Powder',
    price: 80,
    mrp: 90,
    discount: 11,
    description: 'Spicy red chilli powder for authentic Indian taste',
    categoryName: 'Spices & Condiments',
    brand: 'MDH',
    unit: 'packet',
    unitSize: '100g',
    stock: 80,
    minStock: 15,
    tags: ['chilli', 'red', 'spicy', 'powder'],
    imageUrl: '/images/products/chilli-powder.jpg'
  },
  {
    name: 'Garam Masala',
    price: 65,
    mrp: 75,
    discount: 13,
    description: 'Aromatic garam masala blend for Indian curries',
    categoryName: 'Spices & Condiments',
    brand: 'Everest',
    unit: 'packet',
    unitSize: '50g',
    stock: 60,
    minStock: 12,
    tags: ['garam masala', 'spice', 'blend', 'aromatic'],
    imageUrl: '/images/products/garam-masala.jpg'
  },
  {
    name: 'Cumin Seeds (Jeera)',
    price: 180,
    mrp: 200,
    discount: 10,
    description: 'Whole cumin seeds for tempering and flavoring',
    categoryName: 'Spices & Condiments',
    brand: 'Tata Sampann',
    unit: 'kg',
    unitSize: '0.1',
    stock: 40,
    minStock: 8,
    tags: ['cumin', 'jeera', 'seeds', 'tempering'],
    imageUrl: '/images/products/cumin-seeds.jpg'
  },

  // Beverages
  {
    name: 'Tea Leaves (Assam)',
    price: 280,
    mrp: 300,
    discount: 6,
    description: 'Premium Assam tea leaves for strong refreshing tea',
    categoryName: 'Tea & Coffee',
    brand: 'Tata Tea',
    unit: 'packet',
    unitSize: '500g',
    stock: 60,
    minStock: 12,
    isFeatured: true,
    tags: ['tea', 'assam', 'leaves', 'premium'],
    imageUrl: '/images/products/tea-leaves.jpg'
  },
  {
    name: 'Coffee Powder',
    price: 320,
    mrp: 350,
    discount: 8,
    description: 'Filter coffee powder for authentic South Indian coffee',
    categoryName: 'Tea & Coffee',
    brand: 'Bru',
    unit: 'packet',
    unitSize: '500g',
    stock: 40,
    minStock: 8,
    tags: ['coffee', 'powder', 'filter', 'south indian'],
    imageUrl: '/images/products/coffee-powder.jpg'
  },
  {
    name: 'Coca Cola',
    price: 40,
    mrp: 40,
    discount: 0,
    description: 'Refreshing Coca Cola soft drink',
    categoryName: 'Soft Drinks',
    brand: 'Coca Cola',
    unit: 'piece',
    unitSize: '600ml',
    stock: 200,
    minStock: 40,
    tags: ['cola', 'soft drink', 'refreshing'],
    imageUrl: '/images/products/coca-cola.jpg'
  },
  {
    name: 'Mango Juice',
    price: 85,
    mrp: 95,
    discount: 10,
    description: 'Pure mango juice made from Alphonso mangoes',
    categoryName: 'Juices',
    brand: 'Real',
    unit: 'piece',
    unitSize: '1L',
    stock: 80,
    minStock: 15,
    tags: ['mango', 'juice', 'pure', 'alphonso'],
    imageUrl: '/images/products/mango-juice.jpg'
  },
  {
    name: 'Mineral Water',
    price: 20,
    mrp: 20,
    discount: 0,
    description: 'Pure mineral water bottle',
    categoryName: 'Water',
    brand: 'Bisleri',
    unit: 'piece',
    unitSize: '1L',
    stock: 500,
    minStock: 100,
    tags: ['water', 'mineral', 'pure'],
    imageUrl: '/images/products/mineral-water.jpg'
  },

  // Snacks & Confectionery
  {
    name: 'Potato Chips',
    price: 30,
    mrp: 35,
    discount: 14,
    description: 'Crispy potato chips with masala flavor',
    categoryName: 'Snacks & Confectionery',
    brand: 'Lays',
    unit: 'packet',
    unitSize: '50g',
    stock: 150,
    minStock: 30,
    tags: ['chips', 'potato', 'crispy', 'masala'],
    imageUrl: '/images/products/potato-chips.jpg'
  },
  {
    name: 'Biscuits (Marie)',
    price: 25,
    mrp: 30,
    discount: 16,
    description: 'Light and crispy Marie biscuits',
    categoryName: 'Snacks & Confectionery',
    brand: 'Parle',
    unit: 'packet',
    unitSize: '200g',
    stock: 100,
    minStock: 20,
    tags: ['biscuits', 'marie', 'crispy', 'light'],
    imageUrl: '/images/products/marie-biscuits.jpg'
  },
  {
    name: 'Chocolate (Dairy Milk)',
    price: 45,
    mrp: 50,
    discount: 10,
    description: 'Creamy Cadbury Dairy Milk chocolate',
    categoryName: 'Snacks & Confectionery',
    brand: 'Cadbury',
    unit: 'piece',
    unitSize: '38g',
    stock: 200,
    minStock: 40,
    isFeatured: true,
    tags: ['chocolate', 'dairy milk', 'creamy', 'cadbury'],
    imageUrl: '/images/products/dairy-milk.jpg'
  },

  // Personal Care
  {
    name: 'Toothpaste',
    price: 85,
    mrp: 95,
    discount: 10,
    description: 'Fluoride toothpaste for strong teeth',
    categoryName: 'Personal Care',
    brand: 'Colgate',
    unit: 'piece',
    unitSize: '200g',
    stock: 80,
    minStock: 15,
    tags: ['toothpaste', 'fluoride', 'teeth', 'oral care'],
    imageUrl: '/images/products/toothpaste.jpg'
  },
  {
    name: 'Shampoo',
    price: 165,
    mrp: 180,
    discount: 8,
    description: 'Nourishing shampoo for healthy hair',
    categoryName: 'Personal Care',
    brand: 'Head & Shoulders',
    unit: 'piece',
    unitSize: '400ml',
    stock: 60,
    minStock: 12,
    tags: ['shampoo', 'hair care', 'nourishing'],
    imageUrl: '/images/products/shampoo.jpg'
  },
  {
    name: 'Soap',
    price: 35,
    mrp: 40,
    discount: 12,
    description: 'Moisturizing soap for soft skin',
    categoryName: 'Personal Care',
    brand: 'Dove',
    unit: 'piece',
    unitSize: '125g',
    stock: 100,
    minStock: 20,
    tags: ['soap', 'moisturizing', 'soft skin'],
    imageUrl: '/images/products/soap.jpg'
  },

  // Household
  {
    name: 'Dish Wash Liquid',
    price: 95,
    mrp: 105,
    discount: 9,
    description: 'Effective dish wash liquid for clean utensils',
    categoryName: 'Household',
    brand: 'Vim',
    unit: 'piece',
    unitSize: '500ml',
    stock: 80,
    minStock: 15,
    tags: ['dish wash', 'liquid', 'cleaning', 'utensils'],
    imageUrl: '/images/products/dish-wash.jpg'
  },
  {
    name: 'Detergent Powder',
    price: 85,
    mrp: 95,
    discount: 10,
    description: 'Powerful detergent powder for clean clothes',
    categoryName: 'Household',
    brand: 'Surf Excel',
    unit: 'kg',
    unitSize: '1',
    stock: 60,
    minStock: 12,
    tags: ['detergent', 'powder', 'cleaning', 'clothes'],
    imageUrl: '/images/products/detergent.jpg'
  },
  {
    name: 'Toilet Paper',
    price: 45,
    mrp: 50,
    discount: 10,
    description: 'Soft and strong toilet paper rolls',
    categoryName: 'Household',
    brand: 'Origami',
    unit: 'piece',
    unitSize: '4 rolls',
    stock: 100,
    minStock: 20,
    tags: ['toilet paper', 'soft', 'strong'],
    imageUrl: '/images/products/toilet-paper.jpg'
  }
];
